Repository measurement-kit/measurement-kit, pull requests merged in 2019-05, with the labels that each got.

#1795 [ci skip] API documentation improvements
  README.md
  include/measurement_kit/README.md
Labels: documentation

#1794 collector_client: always use production collector
  src/libmeasurement_kit/ooni/collector_client.hpp
Labels: bug

#1793 Upgrade all vendored dependencies for v0.10.2
  include/measurement_kit/internal/collector/collector.h
  include/measurement_kit/internal/vendor/http_parser.h
  include/measurement_kit/internal/vendor/json.hpp
  include/measurement_kit/internal/vendor/mkcollector.hpp
  include/private/catch.hpp
  script/vendor/catch
  script/vendor/http_parser
  script/vendor/json
  script/vendor/mkcollector
  src/libmeasurement_kit/collector/collector.cpp
  src/libmeasurement_kit/vendor/http_parser.c
Labels: enhancement

#1804 Start cleaning up .ci/travis
  .ci/travis/AUTHORS
  .ci/travis/LICENSE
  .ci/travis/README.md
  .ci/travis/alpine/Dockerfile
  .ci/travis/debian/Dockerfile
  .ci/travis/script/cmake
  .ci/travis/script/travis
Labels: cleanup

#1805 .ci/travis: enforce -Werror for builds
  .ci/travis/script/autotools
  .ci/travis/script/travis
  m4/ax_cxx_compile_stdcxx.m4
  m4/mk.m4
Labels: bug

#1798 Allow users to specify software_{name,version} for reuploading measurements
  include/measurement_kit/internal/collector/collector.h
  src/libmeasurement_kit/collector/collector.cpp
Labels: bug

#1785 Fix compilation without deprecated OpenSSL APIs
  src/libmeasurement_kit/net/libssl.hpp
Labels: bug

#1822 [ci skip] README.md: mention .ci/travis
  README.md
Labels: documentation

#1839 HIRL, runnable now more robust to binary data
  configure.ac
  src/libmeasurement_kit/nettests/runnable.cpp
  src/libmeasurement_kit/ooni/http_invalid_request_line.cpp
Labels: OTF, bug, please preserve history

#1843 Release v0.10.4
  Doxyfile
  configure.ac
  include/measurement_kit/README.md
  include/measurement_kit/common/version.h
  include/measurement_kit/common/version.h.in
  include/measurement_kit/internal/vendor/mkcollector.hpp
  include/measurement_kit/internal/vendor/mkcurl.hpp
  include/private/catch.hpp
  script/autoapi/autoapi
  script/update-includes
  script/vendor/catch
  script/vendor/mkcollector
  script/vendor/mkcurl
  src/libmeasurement_kit/engine/autoapi.cpp
  src/libmeasurement_kit/nettests/runnable.cpp
  src/libmeasurement_kit/ooni/http_invalid_request_line.cpp
  src/libmeasurement_kit/ooni/templates_impl.hpp
  src/libmeasurement_kit/ooni/utils.cpp
  src/libmeasurement_kit/ooni/utils.hpp
  src/measurement_kit/cmd/dash.cpp
  src/measurement_kit/cmd/dns_injection.cpp
  src/measurement_kit/cmd/ndt.cpp
  src/measurement_kit/cmd/tcp_connect.cpp
  src/measurement_kit/cmd/web_connectivity.cpp
  src/measurement_kit/cmd/whatsapp.cpp
  src/measurement_kit/cmdline.hpp
  src/measurement_kit/main.cpp
  src/measurement_kit/utils.cpp
Labels: enhancement, please preserve history

#1854 README.md: review and make sure it's up to date
  README.md
  include/measurement_kit/README.md
Labels: documentation
